### ISSUE TITLE
any plans for swift? 

### ISSUE THREAD

**Issue by johndpope** [inamiy/YIDragScrollBar#2]
I need a control like this for swift. 
not aware of this existing anywhere else.

**Comment by inamiy** [comment]
Sorry, I have no plan to convert to Swift, and I don't know any other libs like this.
(Just wonder, is there any problem to use ObjC code?)

**Comment by johndpope** [comment]
it works great with swift project.
need to update demo example / I tried upgrading  Podfile but complained of missing -lPods 

this works great. 
 UIScrollView.setDefaultDragScrollBarEnabled(true)
